image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install App Dependencies
    init: |
      cd backend
      python3 -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
      cd ../frontend
      npm install
